

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www
    env_file: .env
    depends_on:
      - admin_db
      - redis
    networks:
      - app

  
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
    networks:
      - app
  redis:
    image: redis:7
    container_name: laravel-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app

  admin_db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - admin_db_data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - app
  horizon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-horizon
    env_file: .env
    command: php artisan horizon
    restart: unless-stopped
    depends_on:
      - redis
      - server
    networks:
      - app
  scheduler:
    image: php:8.3-cli
    container_name: laravel-scheduler
    volumes:
      - .:/var/www
    entrypoint: |
      sh -c "while true; do
        php /var/www/artisan schedule:run >> /dev/null 2>&1
        sleep 60
      done"

volumes:
  admin_db_data:

networks:
  app:

